# Generated by Django 6.1.1 on 2026-09-21 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_details',
            fields=[
                ('admin_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=240)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin_details',
            },
        ),
        migrations.CreateModel(
            name='card_details',
            fields=[
                ('card_type', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('family_head_name', models.CharField(max_length=100)),
                ('family_head_gender', models.CharField(max_length=100)),
                ('family_head_dob', models.DateField()),
                ('family_head_father_or_husband_name', models.CharField(max_length=100)),
                ('family_native_address', models.CharField(max_length=240)),
                ('family_home_shop_address', models.CharField(max_length=240)),
                ('family_home_shop_number', models.CharField(max_length=15)),
                ('total_family_members_count', models.IntegerField()),
                ('phone', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'db_table': 'card_details',
            },
        ),
        migrations.CreateModel(
            name='card_type_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'card_type_details',
            },
        ),
        migrations.CreateModel(
            name='commodity_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('litre', 'Litre')], default='kg', max_length=10)),
            ],
            options={
                'db_table': 'commodity_details',
            },
        ),
        migrations.CreateModel(
            name='non_pds_commodities',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sales_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('available_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'non_pds_commodities',
            },
        ),
        migrations.CreateModel(
            name='officer_details',
            fields=[
                ('officer_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=240)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'officer_details',
            },
        ),
        migrations.CreateModel(
            name='pds_commodities',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sales_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('available_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'pds_commodities',
            },
        ),
        migrations.CreateModel(
            name='shop_details',
            fields=[
                ('shop_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('address', models.CharField(max_length=240)),
                ('total_card_holders', models.IntegerField()),
            ],
            options={
                'db_table': 'shop_details',
            },
        ),
        migrations.CreateModel(
            name='shop_worker_details',
            fields=[
                ('shop_id', models.CharField(max_length=100)),
                ('shop_worker_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=240)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shop_worker_details',
            },
        ),
        migrations.CreateModel(
            name='commodity_allocation_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('litre', 'Litre')], default='Kg', max_length=10)),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tn_pds_app.card_type_details')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tn_pds_app.commodity_details')),
            ],
            options={
                'db_table': 'commodity_allocation_details',
            },
        ),
        migrations.CreateModel(
            name='consumer_details',
            fields=[
                ('card_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tn_pds_app.card_type_details')),
            ],
            options={
                'db_table': 'consumer_details',
            },
        ),
    ]
