# Generated by Django 6.1.1 on 2026-09-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=100, unique=True)),
                ('family_head_name', models.CharField(max_length=100)),
                ('family_head_gender', models.CharField(max_length=100)),
                ('family_head_dob', models.DateField()),
                ('family_head_father_or_husband_name', models.CharField(max_length=100)),
                ('family_native_address', models.CharField(max_length=240)),
                ('family_home_shop_address', models.CharField(max_length=240)),
                ('family_home_shop_number', models.CharField(max_length=15)),
                ('total_family_members_count', models.IntegerField()),
                ('phone', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'db_table': 'card_details',
            },
        ),
    ]
