# Generated by Django 6.1.1 on 2026-09-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_pds_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='non_pds_commodities',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sales_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('available_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'non_pds_commodities',
            },
        ),
        migrations.CreateModel(
            name='pds_commodities',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sales_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('available_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'pds_commodities',
            },
        ),
        migrations.CreateModel(
            name='shop_details',
            fields=[
                ('shop_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('address', models.CharField(max_length=240)),
                ('total_card_holders', models.IntegerField()),
            ],
            options={
                'db_table': 'shop_details',
            },
        ),
        migrations.CreateModel(
            name='shop_worker_details',
            fields=[
                ('shop_worker_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=240)),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'shop_worker_details',
            },
        ),
        migrations.RemoveField(
            model_name='card_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='card_details',
            name='card_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
