# Generated by Django 6.1.1 on 2026-09-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_pds_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_details',
            name='commodity_image',
            field=models.ImageField(blank=True, null=True, upload_to='commodities/'),
        ),
    ]
