# Generated by Django 6.1.1 on 2026-09-22 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_pds_app', '0002_commodity_details_commodity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_item_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tn_pds_app.commodity_details')),
            ],
            options={
                'db_table': 'cart_item_details',
            },
        ),
    ]
