# Generated by Django 6.1.1 on 2026-09-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_pds_app', '0002_non_pds_commodities_pds_commodities_shop_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='consumer_details',
            fields=[
                ('card_type', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'consumer_details',
            },
        ),
    ]
