# Generated by Django 6.1.1 on 2026-09-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_pds_app', '0003_consumer_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_worker_details',
            old_name='phone',
            new_name='mobile_number',
        ),
        migrations.AddField(
            model_name='shop_worker_details',
            name='password',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop_worker_details',
            name='shop_id',
            field=models.ForeignKey(blank=True, db_column='shop_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='tn_pds_app.shop_details'),
        ),
    ]
