# Generated by Django 6.1.1 on 2026-09-23 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_pds_app', '0003_cart_item_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item_details',
            name='consumer',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='tn_pds_app.consumer_details'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cart_item_details',
            unique_together={('consumer', 'commodity')},
        ),
    ]
