# Generated by Django 6.1.1 on 2026-09-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_pds_app', '0004_rename_phone_shop_worker_details_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_worker_details',
            name='shop_id',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
