# Generated by Django 6.1.1 on 2026-09-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_pds_app', '0005_alter_shop_worker_details_shop_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='officer_details',
            fields=[
                ('officer_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=240)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'officer_details',
            },
        ),
    ]
