# Generated by Django 6.1.1 on 2026-09-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_pds_app', '0007_admin_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_type_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=50)),
            ],
        ),
    ]
