# Generated by Django 6.1.1 on 2026-09-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tn_pds_app', '0008_card_type_details'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card_type_details',
            table='card_type_details',
        ),
    ]
