# Generated by Django 6.1.1 on 2026-09-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_pds_app', '0009_alter_card_type_details_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='commodity_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'commodity_details',
            },
        ),
    ]
