# Generated by Django 6.1.1 on 2026-09-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_pds_app', '0010_commodity_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='commodity_allocation_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tn_pds_app.card_type_details')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tn_pds_app.commodity_details')),
            ],
            options={
                'db_table': 'commodity_allocation_details',
            },
        ),
    ]
