# Generated by Django 6.1.1 on 2026-09-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_pds_app', '0011_commodity_allocation_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_details',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('litre', 'litre')], default='kg', max_length=10),
        ),
    ]
