# Generated by Django 6.1.1 on 2026-09-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_pds_app', '0012_commodity_details_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_allocation_details',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('litre', 'litre')], default='Kg', max_length=10),
        ),
    ]
